import type { Character } from "./types";

export const Characters: Character[] = [
    {
        name: "Nicole",
        id: 1031,
        speciality: "SUPPORT",
        stats: {
            HP_FLAT: 8145,
            ATTACK_FLAT: 649,
            DEFENSE_FLAT: 622,
            CRIT_RATE: 5,
            CRIT_DAMAGE: 50,
            ELEMENT_PERCENT: 0,
            ANOMALY_PROFICIENCY_FLAT: 93,
            ANOMALY_MASTERY_FLAT: 90,
            PEN_PERCENT: 0,
            PEN_FLAT: 0,
            IMPACT_FLAT: 88,
            ENERGY_REGEN_FLAT: 1.56,
        },
    },
    {
        name: "Ben",
        id: 1121,
        speciality: "DEFENSE",
        stats: {
            HP_FLAT: 8577,
            ATTACK_FLAT: 867,
            DEFENSE_FLAT: 724,
            CRIT_RATE: 5,
            CRIT_DAMAGE: 50,
            ELEMENT_PERCENT: 0,
            ANOMALY_PROFICIENCY_FLAT: 90,
            ANOMALY_MASTERY_FLAT: 86,
            PEN_PERCENT: 0,
            PEN_FLAT: 0,
            IMPACT_FLAT: 95,
            ENERGY_REGEN_FLAT: 1.56,
        },
    },
    {
        name: "Anby",
        id: 1011,
        speciality: "STUN",
        stats: {
            HP_FLAT: 7500,
            ATTACK_FLAT: 658,
            DEFENSE_FLAT: 612,
            CRIT_RATE: 5,
            CRIT_DAMAGE: 50,
            ELEMENT_PERCENT: 0,
            ANOMALY_PROFICIENCY_FLAT: 93,
            ANOMALY_MASTERY_FLAT: 94,
            PEN_PERCENT: 0,
            PEN_FLAT: 0,
            IMPACT_FLAT: 136,
            ENERGY_REGEN_FLAT: 1.2,
        },
    },
    {
        name: "Lucy",
        id: 1151,
        speciality: "SUPPORT",
        stats: {
            HP_FLAT: 8025,
            ATTACK_FLAT: 658,
            DEFENSE_FLAT: 612,
            CRIT_RATE: 5,
            CRIT_DAMAGE: 50,
            ELEMENT_PERCENT: 0,
            ANOMALY_PROFICIENCY_FLAT: 93,
            ANOMALY_MASTERY_FLAT: 94,
            PEN_PERCENT: 0,
            PEN_FLAT: 0,
            IMPACT_FLAT: 86,
            ENERGY_REGEN_FLAT: 1.56,
        },
    },
    {
        name: "Soukaku",
        id: 1131,
        speciality: "SUPPORT",
        stats: {
            HP_FLAT: 8025,
            ATTACK_FLAT: 665,
            DEFENSE_FLAT: 597,
            CRIT_RATE: 5,
            CRIT_DAMAGE: 50,
            ELEMENT_PERCENT: 0,
            ANOMALY_PROFICIENCY_FLAT: 96,
            ANOMALY_MASTERY_FLAT: 93,
            PEN_PERCENT: 0,
            PEN_FLAT: 0,
            IMPACT_FLAT: 86,
            ENERGY_REGEN_FLAT: 1.56,
        },
    },
    {
        name: "Rina",
        id: 1211,
        speciality: "SUPPORT",
        stats: {
            HP_FLAT: 8609,
            ATTACK_FLAT: 717,
            DEFENSE_FLAT: 600,
            CRIT_RATE: 5,
            CRIT_DAMAGE: 50,
            ELEMENT_PERCENT: 0,
            ANOMALY_PROFICIENCY_FLAT: 92,
            ANOMALY_MASTERY_FLAT: 93,
            PEN_PERCENT: 14.4,
            PEN_FLAT: 0,
            IMPACT_FLAT: 83,
            ENERGY_REGEN_FLAT: 1.2,
        },
    },
    {
        name: "Lycaon",
        id: 1141,
        speciality: "STUN",
        stats: {
            HP_FLAT: 8416,
            ATTACK_FLAT: 728,
            DEFENSE_FLAT: 606,
            CRIT_RATE: 5,
            CRIT_DAMAGE: 50,
            ELEMENT_PERCENT: 0,
            ANOMALY_PROFICIENCY_FLAT: 90,
            ANOMALY_MASTERY_FLAT: 91,
            PEN_PERCENT: 0,
            PEN_FLAT: 0,
            IMPACT_FLAT: 137,
            ENERGY_REGEN_FLAT: 1.2,
        },
    },
    {
        name: "Koleda",
        id: 1101,
        speciality: "STUN",
        stats: {
            HP_FLAT: 8127,
            ATTACK_FLAT: 735,
            DEFENSE_FLAT: 594,
            CRIT_RATE: 5,
            CRIT_DAMAGE: 50,
            ELEMENT_PERCENT: 0,
            ANOMALY_PROFICIENCY_FLAT: 96,
            ANOMALY_MASTERY_FLAT: 97,
            PEN_PERCENT: 0,
            PEN_FLAT: 0,
            IMPACT_FLAT: 134,
            ENERGY_REGEN_FLAT: 1.2,
        },
    },
    {
        name: "Piper",
        id: 1281,
        speciality: "ANOMALY",
        stats: {
            HP_FLAT: 6976,
            ATTACK_FLAT: 758,
            DEFENSE_FLAT: 613,
            CRIT_RATE: 5,
            CRIT_DAMAGE: 50,
            ELEMENT_PERCENT: 0,
            ANOMALY_PROFICIENCY_FLAT: 118,
            ANOMALY_MASTERY_FLAT: 116,
            PEN_PERCENT: 0,
            PEN_FLAT: 0,
            IMPACT_FLAT: 86,
            ENERGY_REGEN_FLAT: 1.56,
        },
    },
    {
        name: "Billy",
        id: 1081,
        speciality: "ATTACK",
        stats: {
            HP_FLAT: 6907,
            ATTACK_FLAT: 787,
            DEFENSE_FLAT: 606,
            CRIT_RATE: 19.4,
            CRIT_DAMAGE: 50,
            ELEMENT_PERCENT: 0,
            ANOMALY_PROFICIENCY_FLAT: 91,
            ANOMALY_MASTERY_FLAT: 92,
            PEN_PERCENT: 0,
            PEN_FLAT: 0,
            IMPACT_FLAT: 91,
            ENERGY_REGEN_FLAT: 1.2,
        },
    },
    {
        name: "Anton",
        id: 1111,
        speciality: "ATTACK",
        stats: {
            HP_FLAT: 7219,
            ATTACK_FLAT: 791,
            DEFENSE_FLAT: 622,
            CRIT_RATE: 19.4,
            CRIT_DAMAGE: 50,
            ELEMENT_PERCENT: 0,
            ANOMALY_PROFICIENCY_FLAT: 90,
            ANOMALY_MASTERY_FLAT: 86,
            PEN_PERCENT: 0,
            PEN_FLAT: 0,
            IMPACT_FLAT: 95,
            ENERGY_REGEN_FLAT: 1.2,
        },
    },
    {
        name: "Corin",
        id: 1061,
        speciality: "ATTACK",
        stats: {
            HP_FLAT: 6976,
            ATTACK_FLAT: 807,
            DEFENSE_FLAT: 604,
            CRIT_RATE: 5,
            CRIT_DAMAGE: 78.8,
            ELEMENT_PERCENT: 0,
            ANOMALY_PROFICIENCY_FLAT: 96,
            ANOMALY_MASTERY_FLAT: 93,
            PEN_PERCENT: 0,
            PEN_FLAT: 0,
            IMPACT_FLAT: 93,
            ENERGY_REGEN_FLAT: 1.2,
        },
    },
    {
        name: "Grace",
        id: 1181,
        speciality: "ANOMALY",
        stats: {
            HP_FLAT: 7482,
            ATTACK_FLAT: 825,
            DEFENSE_FLAT: 600,
            CRIT_RATE: 5,
            CRIT_DAMAGE: 50,
            ELEMENT_PERCENT: 0,
            ANOMALY_PROFICIENCY_FLAT: 116,
            ANOMALY_MASTERY_FLAT: 151,
            PEN_PERCENT: 0,
            PEN_FLAT: 0,
            IMPACT_FLAT: 83,
            ENERGY_REGEN_FLAT: 1.2,
        },
    },
    {
        name: "Soldier 11",
        id: 1041,
        speciality: "ATTACK",
        stats: {
            HP_FLAT: 7673,
            ATTACK_FLAT: 888,
            DEFENSE_FLAT: 612,
            CRIT_RATE: 19.4,
            CRIT_DAMAGE: 50,
            ELEMENT_PERCENT: 0,
            ANOMALY_PROFICIENCY_FLAT: 93,
            ANOMALY_MASTERY_FLAT: 94,
            PEN_PERCENT: 0,
            PEN_FLAT: 0,
            IMPACT_FLAT: 93,
            ENERGY_REGEN_FLAT: 1.2,
        },
    },
    {
        name: "Nekomata",
        id: 1021,
        speciality: "ATTACK",
        stats: {
            HP_FLAT: 7560,
            ATTACK_FLAT: 910,
            DEFENSE_FLAT: 587,
            CRIT_RATE: 19.4,
            CRIT_DAMAGE: 50,
            ELEMENT_PERCENT: 0,
            ANOMALY_PROFICIENCY_FLAT: 96,
            ANOMALY_MASTERY_FLAT: 97,
            PEN_PERCENT: 0,
            PEN_FLAT: 0,
            IMPACT_FLAT: 92,
            ENERGY_REGEN_FLAT: 1.2,
        },
    },
    {
        name: "Zhu Yuan",
        id: 1241,
        speciality: "ATTACK",
        stats: {
            HP_FLAT: 7482,
            ATTACK_FLAT: 919,
            DEFENSE_FLAT: 600,
            CRIT_RATE: 5,
            CRIT_DAMAGE: 78.8,
            ELEMENT_PERCENT: 0,
            ANOMALY_PROFICIENCY_FLAT: 92,
            ANOMALY_MASTERY_FLAT: 93,
            PEN_PERCENT: 0,
            PEN_FLAT: 0,
            IMPACT_FLAT: 90,
            ENERGY_REGEN_FLAT: 1.2,
        },
    },
    {
        name: "Ellen",
        id: 1191,
        speciality: "ATTACK",
        stats: {
            HP_FLAT: 7673,
            ATTACK_FLAT: 938,
            DEFENSE_FLAT: 606,
            CRIT_RATE: 19.4,
            CRIT_DAMAGE: 50,
            ELEMENT_PERCENT: 0,
            ANOMALY_PROFICIENCY_FLAT: 93,
            ANOMALY_MASTERY_FLAT: 94,
            PEN_PERCENT: 0,
            PEN_FLAT: 0,
            IMPACT_FLAT: 93,
            ENERGY_REGEN_FLAT: 1.2,
        },
    },
    {
        name: "Qingyi",
        id: 1251,
        speciality: "STUN",
        stats: {
            HP_FLAT: 8250,
            ATTACK_FLAT: 758,
            DEFENSE_FLAT: 612,
            CRIT_RATE: 5,
            CRIT_DAMAGE: 50,
            ELEMENT_PERCENT: 0,
            ANOMALY_PROFICIENCY_FLAT: 93,
            ANOMALY_MASTERY_FLAT: 94,
            PEN_PERCENT: 0,
            PEN_FLAT: 0,
            IMPACT_FLAT: 136,
            ENERGY_REGEN_FLAT: 1.2,
        },
    },
    {
        name: "Jane Doe",
        id: 1261,
        speciality: "ANOMALY",
        stats: {
            HP_FLAT: 7788,
            ATTACK_FLAT: 880,
            DEFENSE_FLAT: 606,
            CRIT_RATE: 5,
            CRIT_DAMAGE: 50,
            ELEMENT_PERCENT: 0,
            ANOMALY_PROFICIENCY_FLAT: 114,
            ANOMALY_MASTERY_FLAT: 14,
            PEN_PERCENT: 0,
            PEN_FLAT: 0,
            IMPACT_FLAT: 86,
            ENERGY_REGEN_FLAT: 1.2,
        },
    },
    {
        name: "Seth",
        id: 1271,
        speciality: "DEFENSE",
        stats: {
            HP_FLAT: 8701,
            ATTACK_FLAT: 643,
            DEFENSE_FLAT: 746,
            CRIT_RATE: 5,
            CRIT_DAMAGE: 50,
            ELEMENT_PERCENT: 0,
            ANOMALY_PROFICIENCY_FLAT: 90,
            ANOMALY_MASTERY_FLAT: 86,
            PEN_PERCENT: 0,
            PEN_FLAT: 0,
            IMPACT_FLAT: 94,
            ENERGY_REGEN_FLAT: 1.56,
        },
    },
    {
        name: "Caesar",
        id: 1071,
        speciality: "DEFENSE",
        stats: {
            HP_FLAT: 9526,
            ATTACK_FLAT: 711,
            DEFENSE_FLAT: 753,
            CRIT_RATE: 5,
            CRIT_DAMAGE: 50,
            ELEMENT_PERCENT: 0,
            ANOMALY_PROFICIENCY_FLAT: 90,
            ANOMALY_MASTERY_FLAT: 87,
            PEN_PERCENT: 0,
            PEN_FLAT: 0,
            IMPACT_FLAT: 123,
            ENERGY_REGEN_FLAT: 1.2,
        },
    },
    {
        name: "Burnice",
        id: 1171,
        speciality: "ANOMALY",
        stats: {
            HP_FLAT: 7368,
            ATTACK_FLAT: 863,
            DEFENSE_FLAT: 600,
            CRIT_RATE: 5,
            CRIT_DAMAGE: 50,
            ELEMENT_PERCENT: 0,
            ANOMALY_PROFICIENCY_FLAT: 120,
            ANOMALY_MASTERY_FLAT: 118,
            PEN_PERCENT: 0,
            PEN_FLAT: 0,
            IMPACT_FLAT: 83,
            ENERGY_REGEN_FLAT: 1.56,
        },
    },
    {
        name: "Yanagi",
        id: 1221,
        speciality: "ANOMALY",
        stats: {
            HP_FLAT: 7788,
            ATTACK_FLAT: 872,
            DEFENSE_FLAT: 612,
            CRIT_RATE: 5,
            CRIT_DAMAGE: 50,
            ELEMENT_PERCENT: 0,
            ANOMALY_PROFICIENCY_FLAT: 114,
            ANOMALY_MASTERY_FLAT: 148,
            PEN_PERCENT: 0,
            PEN_FLAT: 0,
            IMPACT_FLAT: 86,
            ENERGY_REGEN_FLAT: 1.2,
        },
    },
    {
        name: "Lighter",
        id: 1161,
        speciality: "STUN",
        stats: {
            HP_FLAT: 8253,
            ATTACK_FLAT: 797,
            DEFENSE_FLAT: 612,
            CRIT_RATE: 5,
            CRIT_DAMAGE: 50,
            ELEMENT_PERCENT: 0,
            ANOMALY_PROFICIENCY_FLAT: 90,
            ANOMALY_MASTERY_FLAT: 91,
            PEN_PERCENT: 0,
            PEN_FLAT: 0,
            IMPACT_FLAT: 137,
            ENERGY_REGEN_FLAT: 1.2,
        },
    },
    {
        name: "Miyabi",
        id: 1091,
        speciality: "ANOMALY",
        stats: {
            HP_FLAT: 7673,
            ATTACK_FLAT: 880,
            DEFENSE_FLAT: 606,
            CRIT_RATE: 5,
            CRIT_DAMAGE: 50,
            ELEMENT_PERCENT: 0,
            ANOMALY_PROFICIENCY_FLAT: 238,
            ANOMALY_MASTERY_FLAT: 116,
            PEN_PERCENT: 0,
            PEN_FLAT: 0,
            IMPACT_FLAT: 86,
            ENERGY_REGEN_FLAT: 1.2,
        },
    },
    {
        name: "Harumasa",
        id: 1201,
        speciality: "ATTACK",
        stats: {
            HP_FLAT: 7405,
            ATTACK_FLAT: 915,
            DEFENSE_FLAT: 600,
            CRIT_RATE: 19.4,
            CRIT_DAMAGE: 50,
            ELEMENT_PERCENT: 0,
            ANOMALY_PROFICIENCY_FLAT: 95,
            ANOMALY_MASTERY_FLAT: 80,
            PEN_PERCENT: 0,
            PEN_FLAT: 0,
            IMPACT_FLAT: 90,
            ENERGY_REGEN_FLAT: 1.2,
        },
    },
    {
        name: "Astra Yao",
        id: 1311,
        speciality: "SUPPORT",
        stats: {
            HP_FLAT: 8609,
            ATTACK_FLAT: 715,
            DEFENSE_FLAT: 600,
            CRIT_RATE: 5,
            CRIT_DAMAGE: 50,
            ELEMENT_PERCENT: 0,
            ANOMALY_PROFICIENCY_FLAT: 92,
            ANOMALY_MASTERY_FLAT: 93,
            PEN_PERCENT: 0,
            PEN_FLAT: 0,
            IMPACT_FLAT: 83,
            ENERGY_REGEN_FLAT: 1.56,
        },
    },
    {
        name: "Evelyn",
        id: 1321,
        speciality: "ATTACK",
        stats: {
            HP_FLAT: 7788,
            ATTACK_FLAT: 929,
            DEFENSE_FLAT: 612,
            CRIT_RATE: 19.4,
            CRIT_DAMAGE: 50,
            ELEMENT_PERCENT: 0,
            ANOMALY_PROFICIENCY_FLAT: 90,
            ANOMALY_MASTERY_FLAT: 92,
            PEN_PERCENT: 0,
            PEN_FLAT: 0,
            IMPACT_FLAT: 93,
            ENERGY_REGEN_FLAT: 1.2,
        },
    },
    {
        name: "Soldier 0 Anby",
        id: 1381,
        speciality: "ATTACK",
        stats: {
            HP_FLAT: 7673,
            ATTACK_FLAT: 929,
            DEFENSE_FLAT: 612,
            CRIT_RATE: 19.4,
            CRIT_DAMAGE: 50,
            ELEMENT_PERCENT: 0,
            ANOMALY_PROFICIENCY_FLAT: 93,
            ANOMALY_MASTERY_FLAT: 94,
            PEN_PERCENT: 0,
            PEN_FLAT: 0,
            IMPACT_FLAT: 93,
            ENERGY_REGEN_FLAT: 1.2,
        },
    },
    {
        name: "Pulchra",
        id: 1351,
        speciality: "STUN",
        stats: {
            HP_FLAT: 7612,
            ATTACK_FLAT: 665,
            DEFENSE_FLAT: 606,
            CRIT_RATE: 5,
            CRIT_DAMAGE: 50,
            ELEMENT_PERCENT: 0,
            ANOMALY_PROFICIENCY_FLAT: 90,
            ANOMALY_MASTERY_FLAT: 92,
            PEN_PERCENT: 0,
            PEN_FLAT: 0,
            IMPACT_FLAT: 136,
            ENERGY_REGEN_FLAT: 1.2,
        },
    },
    {
        name: "Trigger",
        id: 1361,
        speciality: "STUN",
        stats: {
            HP_FLAT: 7923,
            ATTACK_FLAT: 750,
            DEFENSE_FLAT: 600,
            CRIT_RATE: 5,
            CRIT_DAMAGE: 50,
            ELEMENT_PERCENT: 0,
            ANOMALY_PROFICIENCY_FLAT: 95,
            ANOMALY_MASTERY_FLAT: 96,
            PEN_PERCENT: 0,
            PEN_FLAT: 0,
            IMPACT_FLAT: 131,
            ENERGY_REGEN_FLAT: 1.2,
        },
    },
    {
        name: "Vivian",
        id: 1331,
        speciality: "ANOMALY",
        stats: {
            HP_FLAT: 7673,
            ATTACK_FLAT: 880,
            DEFENSE_FLAT: 606,
            CRIT_RATE: 5,
            CRIT_DAMAGE: 50,
            ELEMENT_PERCENT: 0,
            ANOMALY_PROFICIENCY_FLAT: 118,
            ANOMALY_MASTERY_FLAT: 144,
            PEN_PERCENT: 0,
            PEN_FLAT: 0,
            IMPACT_FLAT: 86,
            ENERGY_REGEN_FLAT: 1.2,
        },
    },
    {
        name: "Hugo",
        id: 1291,
        speciality: "ATTACK",
        stats: {
            HP_FLAT: 7940,
            ATTACK_FLAT: 919,
            DEFENSE_FLAT: 616,
            CRIT_RATE: 19.4,
            CRIT_DAMAGE: 50,
            ELEMENT_PERCENT: 0,
            ANOMALY_PROFICIENCY_FLAT: 90,
            ANOMALY_MASTERY_FLAT: 86,
            PEN_PERCENT: 0,
            PEN_FLAT: 0,
            IMPACT_FLAT: 95,
            ENERGY_REGEN_FLAT: 1.2,
        },
    },
    {
        name: "Pan Yinhu",
        id: 1421,
        speciality: "DEFENSE",
        stats: {
            HP_FLAT: 8453,
            ATTACK_FLAT: 661,
            DEFENSE_FLAT: 712,
            CRIT_RATE: 5,
            CRIT_DAMAGE: 50,
            ELEMENT_PERCENT: 0,
            ANOMALY_PROFICIENCY_FLAT: 90,
            ANOMALY_MASTERY_FLAT: 91,
            PEN_PERCENT: 0,
            PEN_FLAT: 0,
            IMPACT_FLAT: 94,
            ENERGY_REGEN_FLAT: 1.56,
        },
    },
    {
        name: "Yixuan",
        id: 1371,
        speciality: "RUPTURE",
        stats: {
            HP_FLAT: 8373,
            ATTACK_FLAT: 872,
            DEFENSE_FLAT: 441,
            CRIT_RATE: 19.4,
            CRIT_DAMAGE: 50,
            ELEMENT_PERCENT: 0,
            ANOMALY_PROFICIENCY_FLAT: 90,
            ANOMALY_MASTERY_FLAT: 92,
            PEN_PERCENT: 0,
            PEN_FLAT: 0,
            IMPACT_FLAT: 93,
            ENERGY_REGEN_FLAT: 2,
        },
    },
    {
        name: "Ju Fufu",
        id: 1391,
        speciality: "STUN",
        stats: {
            HP_FLAT: 8250,
            ATTACK_FLAT: 765,
            DEFENSE_FLAT: 597,
            CRIT_RATE: 19.4,
            CRIT_DAMAGE: 50,
            ELEMENT_PERCENT: 0,
            ANOMALY_PROFICIENCY_FLAT: 96,
            ANOMALY_MASTERY_FLAT: 93,
            PEN_PERCENT: 0,
            PEN_FLAT: 0,
            IMPACT_FLAT: 118,
            ENERGY_REGEN_FLAT: 1.2,
        },
    },
    {
        name: "Yuzuha",
        id: 1411,
        speciality: "SUPPORT",
        stats: {
            HP_FLAT: 8829,
            ATTACK_FLAT: 758,
            DEFENSE_FLAT: 612,
            CRIT_RATE: 5,
            CRIT_DAMAGE: 50,
            ELEMENT_PERCENT: 0,
            ANOMALY_PROFICIENCY_FLAT: 93,
            ANOMALY_MASTERY_FLAT: 124,
            PEN_PERCENT: 0,
            PEN_FLAT: 0,
            IMPACT_FLAT: 86,
            ENERGY_REGEN_FLAT: 1.2,
        },
    },
    {
        name: "Alice",
        id: 1401,
        speciality: "ANOMALY",
        stats: {
            HP_FLAT: 7673,
            ATTACK_FLAT: 880,
            DEFENSE_FLAT: 606,
            CRIT_RATE: 5,
            CRIT_DAMAGE: 50,
            ELEMENT_PERCENT: 0,
            ANOMALY_PROFICIENCY_FLAT: 118,
            ANOMALY_MASTERY_FLAT: 142,
            PEN_PERCENT: 0,
            PEN_FLAT: 0,
            IMPACT_FLAT: 86,
            ENERGY_REGEN_FLAT: 1.2,
        },
    },
    {
        name: "Seed",
        id: 1461,
        speciality: "ATTACK",
        stats: {
            HP_FLAT: 7673,
            ATTACK_FLAT: 929,
            DEFENSE_FLAT: 612,
            CRIT_RATE: 5,
            CRIT_DAMAGE: 78.8,
            ELEMENT_PERCENT: 0,
            ANOMALY_PROFICIENCY_FLAT: 93,
            ANOMALY_MASTERY_FLAT: 94,
            PEN_PERCENT: 0,
            PEN_FLAT: 0,
            IMPACT_FLAT: 93,
            ENERGY_REGEN_FLAT: 1.2,
        },
    },
    {
        name: "Orphie & Magus",
        id: 1301,
        speciality: "ATTACK",
        stats: {
            HP_FLAT: 7788,
            ATTACK_FLAT: 929,
            DEFENSE_FLAT: 612,
            CRIT_RATE: 5,
            CRIT_DAMAGE: 50,
            ELEMENT_PERCENT: 0,
            ANOMALY_PROFICIENCY_FLAT: 90,
            ANOMALY_MASTERY_FLAT: 92,
            PEN_PERCENT: 0,
            PEN_FLAT: 0,
            IMPACT_FLAT: 93,
            ENERGY_REGEN_FLAT: 1.56,
        },
    },
    {
        name: "Lucia",
        id: 1451,
        speciality: "SUPPORT",
        stats: {
            HP_FLAT: 8477,
            ATTACK_FLAT: 758,
            DEFENSE_FLAT: 594,
            CRIT_RATE: 5,
            CRIT_DAMAGE: 50,
            ELEMENT_PERCENT: 0,
            ANOMALY_PROFICIENCY_FLAT: 95,
            ANOMALY_MASTERY_FLAT: 96,
            PEN_PERCENT: 0,
            PEN_FLAT: 0,
            IMPACT_FLAT: 83,
            ENERGY_REGEN_FLAT: 1.56,
        },
    },
    {
        name: "Manato",
        id: 1441,
        speciality: "RUPTURE",
        stats: {
            HP_FLAT: 7724,
            ATTACK_FLAT: 755,
            DEFENSE_FLAT: 443,
            CRIT_RATE: 5,
            CRIT_DAMAGE: 50,
            ELEMENT_PERCENT: 0,
            ANOMALY_PROFICIENCY_FLAT: 90,
            ANOMALY_MASTERY_FLAT: 87,
            PEN_PERCENT: 0,
            PEN_FLAT: 0,
            IMPACT_FLAT: 95,
            ENERGY_REGEN_FLAT: 1.2,
        },
    },
    {
        name: "Yidhari",
        id: 1051,
        speciality: "RUPTURE",
        stats: {
            HP_FLAT: 8497,
            ATTACK_FLAT: 859,
            DEFENSE_FLAT: 448,
            CRIT_RATE: 19.4,
            CRIT_DAMAGE: 50,
            ELEMENT_PERCENT: 0,
            ANOMALY_PROFICIENCY_FLAT: 90,
            ANOMALY_MASTERY_FLAT: 87,
            PEN_PERCENT: 0,
            PEN_FLAT: 0,
            IMPACT_FLAT: 95,
            ENERGY_REGEN_FLAT: 2,
        },
    },
    {
        name: "Dialyn",
        id: 1481,
        speciality: "STUN",
        stats: {
            HP_FLAT: 8250,
            ATTACK_FLAT: 758,
            DEFENSE_FLAT: 612,
            CRIT_RATE: 19.4,
            CRIT_DAMAGE: 50,
            ELEMENT_PERCENT: 0,
            ANOMALY_PROFICIENCY_FLAT: 93,
            ANOMALY_MASTERY_FLAT: 94,
            PEN_PERCENT: 0,
            PEN_FLAT: 0,
            IMPACT_FLAT: 110,
            ENERGY_REGEN_FLAT: 1.2,
        },
    },


    
];
