import type { Character } from "./types";

export const Characters: Character[] = [
    {
        name: "Nicole",
        speciality: "SUPPORT",
        stats: {
            HP_FLAT: 8145,
            ATTACK_FLAT: 649,
            DEFENSE_FLAT: 622,
            CRIT_RATE: 5,
            CRIT_DAMAGE: 50,
            ELEMENT_PERCENT: 0,
            ANOMALY_PROFICIENCY_FLAT: 93,
            ANOMALY_MASTERY_FLAT: 90,
            PEN_PERCENT: 0,
            PEN_FLAT: 0,
            IMPACT_FLAT: 88,
            ENERGY_REGEN_FLAT: 1.56,
        },
    },
    {
        name: "Ben",
        speciality: "DEFENSE",
        stats: {
            HP_FLAT: 8577,
            ATTACK_FLAT: 867,
            DEFENSE_FLAT: 724,
            CRIT_RATE: 5,
            CRIT_DAMAGE: 50,
            ELEMENT_PERCENT: 0,
            ANOMALY_PROFICIENCY_FLAT: 90,
            ANOMALY_MASTERY_FLAT: 86,
            PEN_PERCENT: 0,
            PEN_FLAT: 0,
            IMPACT_FLAT: 95,
            ENERGY_REGEN_FLAT: 1.56,
        },
    },
    {
        name: "Anby",
        speciality: "STUN",
        stats: {
            HP_FLAT: 7500,
            ATTACK_FLAT: 658,
            DEFENSE_FLAT: 612,
            CRIT_RATE: 5,
            CRIT_DAMAGE: 50,
            ELEMENT_PERCENT: 0,
            ANOMALY_PROFICIENCY_FLAT: 93,
            ANOMALY_MASTERY_FLAT: 94,
            PEN_PERCENT: 0,
            PEN_FLAT: 0,
            IMPACT_FLAT: 136,
            ENERGY_REGEN_FLAT: 1.2,
        },
    },
    {
        name: "Lucy",
        speciality: "SUPPORT",
        stats: {
            HP_FLAT: 8025,
            ATTACK_FLAT: 658,
            DEFENSE_FLAT: 612,
            CRIT_RATE: 5,
            CRIT_DAMAGE: 50,
            ELEMENT_PERCENT: 0,
            ANOMALY_PROFICIENCY_FLAT: 93,
            ANOMALY_MASTERY_FLAT: 94,
            PEN_PERCENT: 0,
            PEN_FLAT: 0,
            IMPACT_FLAT: 86,
            ENERGY_REGEN_FLAT: 1.56,
        },
    },
    {
        name: "Soukaku",
        speciality: "SUPPORT",
        stats: {
            HP_FLAT: 8025,
            ATTACK_FLAT: 665,
            DEFENSE_FLAT: 597,
            CRIT_RATE: 5,
            CRIT_DAMAGE: 50,
            ELEMENT_PERCENT: 0,
            ANOMALY_PROFICIENCY_FLAT: 96,
            ANOMALY_MASTERY_FLAT: 93,
            PEN_PERCENT: 0,
            PEN_FLAT: 0,
            IMPACT_FLAT: 86,
            ENERGY_REGEN_FLAT: 1.56,
        },
    },
    {
        name: "Rina",
        speciality: "SUPPORT",
        stats: {
            HP_FLAT: 8609,
            ATTACK_FLAT: 717,
            DEFENSE_FLAT: 600,
            CRIT_RATE: 5,
            CRIT_DAMAGE: 50,
            ELEMENT_PERCENT: 0,
            ANOMALY_PROFICIENCY_FLAT: 92,
            ANOMALY_MASTERY_FLAT: 93,
            PEN_PERCENT: 14.4,
            PEN_FLAT: 0,
            IMPACT_FLAT: 83,
            ENERGY_REGEN_FLAT: 1.2,
        },
    },
    {
        name: "Lycaon",
        speciality: "STUN",
        stats: {
            HP_FLAT: 8416,
            ATTACK_FLAT: 728,
            DEFENSE_FLAT: 606,
            CRIT_RATE: 5,
            CRIT_DAMAGE: 50,
            ELEMENT_PERCENT: 0,
            ANOMALY_PROFICIENCY_FLAT: 90,
            ANOMALY_MASTERY_FLAT: 91,
            PEN_PERCENT: 0,
            PEN_FLAT: 0,
            IMPACT_FLAT: 137,
            ENERGY_REGEN_FLAT: 1.2,
        },
    },
    {
        name: "Koleda",
        speciality: "STUN",
        stats: {
            HP_FLAT: 8127,
            ATTACK_FLAT: 735,
            DEFENSE_FLAT: 594,
            CRIT_RATE: 5,
            CRIT_DAMAGE: 50,
            ELEMENT_PERCENT: 0,
            ANOMALY_PROFICIENCY_FLAT: 96,
            ANOMALY_MASTERY_FLAT: 97,
            PEN_PERCENT: 0,
            PEN_FLAT: 0,
            IMPACT_FLAT: 134,
            ENERGY_REGEN_FLAT: 1.2,
        },
    },
    {
        name: "Piper",
        speciality: "ANOMALY",
        stats: {
            HP_FLAT: 6976,
            ATTACK_FLAT: 758,
            DEFENSE_FLAT: 613,
            CRIT_RATE: 5,
            CRIT_DAMAGE: 50,
            ELEMENT_PERCENT: 0,
            ANOMALY_PROFICIENCY_FLAT: 118,
            ANOMALY_MASTERY_FLAT: 116,
            PEN_PERCENT: 0,
            PEN_FLAT: 0,
            IMPACT_FLAT: 86,
            ENERGY_REGEN_FLAT: 1.56,
        },
    },
    {
        name: "Billy",
        speciality: "ATTACK",
        stats: {
            HP_FLAT: 6907,
            ATTACK_FLAT: 787,
            DEFENSE_FLAT: 606,
            CRIT_RATE: 19.4,
            CRIT_DAMAGE: 50,
            ELEMENT_PERCENT: 0,
            ANOMALY_PROFICIENCY_FLAT: 91,
            ANOMALY_MASTERY_FLAT: 92,
            PEN_PERCENT: 0,
            PEN_FLAT: 0,
            IMPACT_FLAT: 91,
            ENERGY_REGEN_FLAT: 1.2,
        },
    },
    {
        name: "Anton",
        speciality: "ATTACK",
        stats: {
            HP_FLAT: 7219,
            ATTACK_FLAT: 791,
            DEFENSE_FLAT: 622,
            CRIT_RATE: 19.4,
            CRIT_DAMAGE: 50,
            ELEMENT_PERCENT: 0,
            ANOMALY_PROFICIENCY_FLAT: 90,
            ANOMALY_MASTERY_FLAT: 86,
            PEN_PERCENT: 0,
            PEN_FLAT: 0,
            IMPACT_FLAT: 95,
            ENERGY_REGEN_FLAT: 1.2,
        },
    },
    {
        name: "Corin",
        speciality: "ATTACK",
        stats: {
            HP_FLAT: 6976,
            ATTACK_FLAT: 807,
            DEFENSE_FLAT: 604,
            CRIT_RATE: 5,
            CRIT_DAMAGE: 78.8,
            ELEMENT_PERCENT: 0,
            ANOMALY_PROFICIENCY_FLAT: 96,
            ANOMALY_MASTERY_FLAT: 93,
            PEN_PERCENT: 0,
            PEN_FLAT: 0,
            IMPACT_FLAT: 93,
            ENERGY_REGEN_FLAT: 1.2,
        },
    },
    {
        name: "Grace",
        speciality: "ANOMALY",
        stats: {
            HP_FLAT: 7482,
            ATTACK_FLAT: 825,
            DEFENSE_FLAT: 600,
            CRIT_RATE: 5,
            CRIT_DAMAGE: 50,
            ELEMENT_PERCENT: 0,
            ANOMALY_PROFICIENCY_FLAT: 116,
            ANOMALY_MASTERY_FLAT: 151,
            PEN_PERCENT: 0,
            PEN_FLAT: 0,
            IMPACT_FLAT: 83,
            ENERGY_REGEN_FLAT: 1.2,
        },
    },
    {
        name: "Soldier 11",
        speciality: "ATTACK",
        stats: {
            HP_FLAT: 7673,
            ATTACK_FLAT: 888,
            DEFENSE_FLAT: 612,
            CRIT_RATE: 19.4,
            CRIT_DAMAGE: 50,
            ELEMENT_PERCENT: 0,
            ANOMALY_PROFICIENCY_FLAT: 93,
            ANOMALY_MASTERY_FLAT: 94,
            PEN_PERCENT: 0,
            PEN_FLAT: 0,
            IMPACT_FLAT: 93,
            ENERGY_REGEN_FLAT: 1.2,
        },
    },
    {
        name: "Nekomata",
        speciality: "ATTACK",
        stats: {
            HP_FLAT: 7560,
            ATTACK_FLAT: 910,
            DEFENSE_FLAT: 587,
            CRIT_RATE: 19.4,
            CRIT_DAMAGE: 50,
            ELEMENT_PERCENT: 0,
            ANOMALY_PROFICIENCY_FLAT: 96,
            ANOMALY_MASTERY_FLAT: 97,
            PEN_PERCENT: 0,
            PEN_FLAT: 0,
            IMPACT_FLAT: 92,
            ENERGY_REGEN_FLAT: 1.2,
        },
    },
    {
        name: "Zhu Yuan",
        speciality: "ATTACK",
        stats: {
            HP_FLAT: 7482,
            ATTACK_FLAT: 919,
            DEFENSE_FLAT: 600,
            CRIT_RATE: 5,
            CRIT_DAMAGE: 78.8,
            ELEMENT_PERCENT: 0,
            ANOMALY_PROFICIENCY_FLAT: 92,
            ANOMALY_MASTERY_FLAT: 93,
            PEN_PERCENT: 0,
            PEN_FLAT: 0,
            IMPACT_FLAT: 90,
            ENERGY_REGEN_FLAT: 1.2,
        },
    },
    {
        name: "Ellen",
        speciality: "ATTACK",
        stats: {
            HP_FLAT: 7673,
            ATTACK_FLAT: 938,
            DEFENSE_FLAT: 606,
            CRIT_RATE: 19.4,
            CRIT_DAMAGE: 50,
            ELEMENT_PERCENT: 0,
            ANOMALY_PROFICIENCY_FLAT: 93,
            ANOMALY_MASTERY_FLAT: 94,
            PEN_PERCENT: 0,
            PEN_FLAT: 0,
            IMPACT_FLAT: 93,
            ENERGY_REGEN_FLAT: 1.2,
        },
    },
    {
        name: "Qingyi",
        speciality: "STUN",
        stats: {
            HP_FLAT: 8250,
            ATTACK_FLAT: 758,
            DEFENSE_FLAT: 612,
            CRIT_RATE: 5,
            CRIT_DAMAGE: 50,
            ELEMENT_PERCENT: 0,
            ANOMALY_PROFICIENCY_FLAT: 93,
            ANOMALY_MASTERY_FLAT: 94,
            PEN_PERCENT: 0,
            PEN_FLAT: 0,
            IMPACT_FLAT: 136,
            ENERGY_REGEN_FLAT: 1.2,
        },
    },
    {
        name: "Jane Doe",
        speciality: "ANOMALY",
        stats: {
            HP_FLAT: 7788,
            ATTACK_FLAT: 880,
            DEFENSE_FLAT: 606,
            CRIT_RATE: 5,
            CRIT_DAMAGE: 50,
            ELEMENT_PERCENT: 0,
            ANOMALY_PROFICIENCY_FLAT: 114,
            ANOMALY_MASTERY_FLAT: 14,
            PEN_PERCENT: 0,
            PEN_FLAT: 0,
            IMPACT_FLAT: 86,
            ENERGY_REGEN_FLAT: 1.2,
        },
    },
    {
        name: "Seth",
        speciality: "DEFENSE",
        stats: {
            HP_FLAT: 8701,
            ATTACK_FLAT: 643,
            DEFENSE_FLAT: 746,
            CRIT_RATE: 5,
            CRIT_DAMAGE: 50,
            ELEMENT_PERCENT: 0,
            ANOMALY_PROFICIENCY_FLAT: 90,
            ANOMALY_MASTERY_FLAT: 86,
            PEN_PERCENT: 0,
            PEN_FLAT: 0,
            IMPACT_FLAT: 94,
            ENERGY_REGEN_FLAT: 1.56,
        },
    },
    {
        name: "Caesar",
        speciality: "DEFENSE",
        stats: {
            HP_FLAT: 9526,
            ATTACK_FLAT: 711,
            DEFENSE_FLAT: 753,
            CRIT_RATE: 5,
            CRIT_DAMAGE: 50,
            ELEMENT_PERCENT: 0,
            ANOMALY_PROFICIENCY_FLAT: 90,
            ANOMALY_MASTERY_FLAT: 87,
            PEN_PERCENT: 0,
            PEN_FLAT: 0,
            IMPACT_FLAT: 123,
            ENERGY_REGEN_FLAT: 1.2,
        },
    },
    {
        name: "Burnice",
        speciality: "ANOMALY",
        stats: {
            HP_FLAT: 7368,
            ATTACK_FLAT: 863,
            DEFENSE_FLAT: 600,
            CRIT_RATE: 5,
            CRIT_DAMAGE: 50,
            ELEMENT_PERCENT: 0,
            ANOMALY_PROFICIENCY_FLAT: 120,
            ANOMALY_MASTERY_FLAT: 118,
            PEN_PERCENT: 0,
            PEN_FLAT: 0,
            IMPACT_FLAT: 83,
            ENERGY_REGEN_FLAT: 1.56,
        },
    },
    {
        name: "Yanagi",
        speciality: "ANOMALY",
        stats: {
            HP_FLAT: 7788,
            ATTACK_FLAT: 872,
            DEFENSE_FLAT: 612,
            CRIT_RATE: 5,
            CRIT_DAMAGE: 50,
            ELEMENT_PERCENT: 0,
            ANOMALY_PROFICIENCY_FLAT: 114,
            ANOMALY_MASTERY_FLAT: 148,
            PEN_PERCENT: 0,
            PEN_FLAT: 0,
            IMPACT_FLAT: 86,
            ENERGY_REGEN_FLAT: 1.2,
        },
    },
    {
        name: "Lighter",
        speciality: "STUN",
        stats: {
            HP_FLAT: 8253,
            ATTACK_FLAT: 797,
            DEFENSE_FLAT: 612,
            CRIT_RATE: 5,
            CRIT_DAMAGE: 50,
            ELEMENT_PERCENT: 0,
            ANOMALY_PROFICIENCY_FLAT: 90,
            ANOMALY_MASTERY_FLAT: 91,
            PEN_PERCENT: 0,
            PEN_FLAT: 0,
            IMPACT_FLAT: 137,
            ENERGY_REGEN_FLAT: 1.2,
        },
    },
    {
        name: "Miyabi",
        speciality: "ANOMALY",
        stats: {
            HP_FLAT: 7673,
            ATTACK_FLAT: 880,
            DEFENSE_FLAT: 606,
            CRIT_RATE: 5,
            CRIT_DAMAGE: 50,
            ELEMENT_PERCENT: 0,
            ANOMALY_PROFICIENCY_FLAT: 238,
            ANOMALY_MASTERY_FLAT: 116,
            PEN_PERCENT: 0,
            PEN_FLAT: 0,
            IMPACT_FLAT: 86,
            ENERGY_REGEN_FLAT: 1.2,
        },
    },
    {
        name: "Harumasa",
        speciality: "ATTACK",
        stats: {
            HP_FLAT: 7405,
            ATTACK_FLAT: 915,
            DEFENSE_FLAT: 600,
            CRIT_RATE: 19.4,
            CRIT_DAMAGE: 50,
            ELEMENT_PERCENT: 0,
            ANOMALY_PROFICIENCY_FLAT: 95,
            ANOMALY_MASTERY_FLAT: 80,
            PEN_PERCENT: 0,
            PEN_FLAT: 0,
            IMPACT_FLAT: 90,
            ENERGY_REGEN_FLAT: 1.2,
        },
    },
    {
        name: "Astra Yao",
        speciality: "SUPPORT",
        stats: {
            HP_FLAT: 8609,
            ATTACK_FLAT: 715,
            DEFENSE_FLAT: 600,
            CRIT_RATE: 5,
            CRIT_DAMAGE: 50,
            ELEMENT_PERCENT: 0,
            ANOMALY_PROFICIENCY_FLAT: 92,
            ANOMALY_MASTERY_FLAT: 93,
            PEN_PERCENT: 0,
            PEN_FLAT: 0,
            IMPACT_FLAT: 83,
            ENERGY_REGEN_FLAT: 1.56,
        },
    },
    {
        name: "Evelyn",
        speciality: "ATTACK",
        stats: {
            HP_FLAT: 7788,
            ATTACK_FLAT: 929,
            DEFENSE_FLAT: 612,
            CRIT_RATE: 19.4,
            CRIT_DAMAGE: 50,
            ELEMENT_PERCENT: 0,
            ANOMALY_PROFICIENCY_FLAT: 90,
            ANOMALY_MASTERY_FLAT: 92,
            PEN_PERCENT: 0,
            PEN_FLAT: 0,
            IMPACT_FLAT: 93,
            ENERGY_REGEN_FLAT: 1.2,
        },
    },
    {
        name: "Anby: Soldier 0",
        speciality: "ATTACK",
        stats: {
            HP_FLAT: 7673,
            ATTACK_FLAT: 929,
            DEFENSE_FLAT: 612,
            CRIT_RATE: 19.4,
            CRIT_DAMAGE: 50,
            ELEMENT_PERCENT: 0,
            ANOMALY_PROFICIENCY_FLAT: 93,
            ANOMALY_MASTERY_FLAT: 94,
            PEN_PERCENT: 0,
            PEN_FLAT: 0,
            IMPACT_FLAT: 93,
            ENERGY_REGEN_FLAT: 1.2,
        },
    },
    {
        name: "Pulchra",
        speciality: "STUN",
        stats: {
            HP_FLAT: 7612,
            ATTACK_FLAT: 665,
            DEFENSE_FLAT: 606,
            CRIT_RATE: 5,
            CRIT_DAMAGE: 50,
            ELEMENT_PERCENT: 0,
            ANOMALY_PROFICIENCY_FLAT: 90,
            ANOMALY_MASTERY_FLAT: 92,
            PEN_PERCENT: 0,
            PEN_FLAT: 0,
            IMPACT_FLAT: 136,
            ENERGY_REGEN_FLAT: 1.2,
        },
    },
    {
        name: "Trigger",
        speciality: "STUN",
        stats: {
            HP_FLAT: 7923,
            ATTACK_FLAT: 750,
            DEFENSE_FLAT: 600,
            CRIT_RATE: 5,
            CRIT_DAMAGE: 50,
            ELEMENT_PERCENT: 0,
            ANOMALY_PROFICIENCY_FLAT: 95,
            ANOMALY_MASTERY_FLAT: 96,
            PEN_PERCENT: 0,
            PEN_FLAT: 0,
            IMPACT_FLAT: 131,
            ENERGY_REGEN_FLAT: 1.2,
        },
    },
    {
        name: "Vivian",
        speciality: "ANOMALY",
        stats: {
            HP_FLAT: 7673,
            ATTACK_FLAT: 880,
            DEFENSE_FLAT: 606,
            CRIT_RATE: 5,
            CRIT_DAMAGE: 50,
            ELEMENT_PERCENT: 0,
            ANOMALY_PROFICIENCY_FLAT: 118,
            ANOMALY_MASTERY_FLAT: 144,
            PEN_PERCENT: 0,
            PEN_FLAT: 0,
            IMPACT_FLAT: 86,
            ENERGY_REGEN_FLAT: 1.2,
        },
    },
    {
        name: "Hugo",
        speciality: "ATTACK",
        stats: {
            HP_FLAT: 7940,
            ATTACK_FLAT: 919,
            DEFENSE_FLAT: 616,
            CRIT_RATE: 19.4,
            CRIT_DAMAGE: 50,
            ELEMENT_PERCENT: 0,
            ANOMALY_PROFICIENCY_FLAT: 90,
            ANOMALY_MASTERY_FLAT: 86,
            PEN_PERCENT: 0,
            PEN_FLAT: 0,
            IMPACT_FLAT: 95,
            ENERGY_REGEN_FLAT: 1.2,
        },
    },
    {
        name: "Pan Yinhu",
        speciality: "DEFENSE",
        stats: {
            HP_FLAT: 8453,
            ATTACK_FLAT: 661,
            DEFENSE_FLAT: 712,
            CRIT_RATE: 5,
            CRIT_DAMAGE: 50,
            ELEMENT_PERCENT: 0,
            ANOMALY_PROFICIENCY_FLAT: 90,
            ANOMALY_MASTERY_FLAT: 91,
            PEN_PERCENT: 0,
            PEN_FLAT: 0,
            IMPACT_FLAT: 94,
            ENERGY_REGEN_FLAT: 1.56,
        },
    },
    {
        name: "Yixuan",
        speciality: "RUPTURE",
        stats: {
            HP_FLAT: 8373,
            ATTACK_FLAT: 872,
            DEFENSE_FLAT: 441,
            CRIT_RATE: 19.4,
            CRIT_DAMAGE: 50,
            ELEMENT_PERCENT: 0,
            ANOMALY_PROFICIENCY_FLAT: 90,
            ANOMALY_MASTERY_FLAT: 92,
            PEN_PERCENT: 0,
            PEN_FLAT: 0,
            IMPACT_FLAT: 93,
            ENERGY_REGEN_FLAT: 1.2,
        },
    },
    {
        name: "Ju Fufu",
        speciality: "STUN",
        stats: {
            HP_FLAT: 8250,
            ATTACK_FLAT: 765,
            DEFENSE_FLAT: 597,
            CRIT_RATE: 19.4,
            CRIT_DAMAGE: 50,
            ELEMENT_PERCENT: 0,
            ANOMALY_PROFICIENCY_FLAT: 96,
            ANOMALY_MASTERY_FLAT: 93,
            PEN_PERCENT: 0,
            PEN_FLAT: 0,
            IMPACT_FLAT: 118,
            ENERGY_REGEN_FLAT: 1.2,
        },
    },
    {
        name: "Yuzuha",
        speciality: "SUPPORT",
        stats: {
            HP_FLAT: 8829,
            ATTACK_FLAT: 758,
            DEFENSE_FLAT: 612,
            CRIT_RATE: 5,
            CRIT_DAMAGE: 50,
            ELEMENT_PERCENT: 0,
            ANOMALY_PROFICIENCY_FLAT: 93,
            ANOMALY_MASTERY_FLAT: 124,
            PEN_PERCENT: 0,
            PEN_FLAT: 0,
            IMPACT_FLAT: 86,
            ENERGY_REGEN_FLAT: 1.2,
        },
    },
    {
        name: "Alice",
        speciality: "ANOMALY",
        stats: {
            HP_FLAT: 7673,
            ATTACK_FLAT: 880,
            DEFENSE_FLAT: 606,
            CRIT_RATE: 5,
            CRIT_DAMAGE: 50,
            ELEMENT_PERCENT: 0,
            ANOMALY_PROFICIENCY_FLAT: 118,
            ANOMALY_MASTERY_FLAT: 142,
            PEN_PERCENT: 0,
            PEN_FLAT: 0,
            IMPACT_FLAT: 86,
            ENERGY_REGEN_FLAT: 1.2,
        },
    },
    {
        name: "Seed",
        speciality: "ATTACK",
        stats: {
            HP_FLAT: 7673,
            ATTACK_FLAT: 929,
            DEFENSE_FLAT: 612,
            CRIT_RATE: 5,
            CRIT_DAMAGE: 78.8,
            ELEMENT_PERCENT: 0,
            ANOMALY_PROFICIENCY_FLAT: 93,
            ANOMALY_MASTERY_FLAT: 94,
            PEN_PERCENT: 0,
            PEN_FLAT: 0,
            IMPACT_FLAT: 93,
            ENERGY_REGEN_FLAT: 1.2,
        },
    },
    {
        name: "Orphie & Magus",
        speciality: "ATTACK",
        stats: {
            HP_FLAT: 7788,
            ATTACK_FLAT: 929,
            DEFENSE_FLAT: 612,
            CRIT_RATE: 5,
            CRIT_DAMAGE: 50,
            ELEMENT_PERCENT: 0,
            ANOMALY_PROFICIENCY_FLAT: 90,
            ANOMALY_MASTERY_FLAT: 92,
            PEN_PERCENT: 0,
            PEN_FLAT: 0,
            IMPACT_FLAT: 93,
            ENERGY_REGEN_FLAT: 1.56,
        },
    },
];
