import type { Wengine } from "./types";

export const Wengines: Wengine[] = [
    {
        name: "Bellicose Blaze",
        speciality: "ATTACK",
        WengineStatSelected: "ENERGY_REGEN_PERCENT",
        WengineFlatAttack: 713,
        WengineStatValue: 60,
    },
    {
        name: "Cordis Germina",
        speciality: "ATTACK",
        WengineStatSelected: "CRIT_RATE",
        WengineFlatAttack: 713,
        WengineStatValue: 24,
    },
    {
        name: "Practiced Perfection",
        speciality: "ANOMALY",
        WengineStatSelected: "ATTACK_PERCENT",
        WengineFlatAttack: 713,
        WengineStatValue: 30,
    },
    {
        name: "Metanukimorphosis",
        speciality: "SUPPORT",
        WengineStatSelected: "ENERGY_REGEN_PERCENT",
        WengineFlatAttack: 713,
        WengineStatValue: 60,
    },
    {
        name: "[Cinder] Cobalt",
        speciality: "RUPTURE",
        WengineStatSelected: "HP_PERCENT",
        WengineFlatAttack: 475,
        WengineStatValue: 20,
    },
    {
        name: "Reel Projector",
        speciality: "DEFENSE",
        WengineStatSelected: "IMPACT_FLAT",
        WengineFlatAttack: 594,
        WengineStatValue: 15,
    },
    {
        name: "Roaring Fur-nace",
        speciality: "STUN",
        WengineStatSelected: "ATTACK_PERCENT",
        WengineFlatAttack: 713,
        WengineStatValue: 30,
    },
    {
        name: "Tremor Trigram Vessel",
        speciality: "DEFENSE",
        WengineStatSelected: "ATTACK_PERCENT",
        WengineFlatAttack: 624,
        WengineStatValue: 25,
    },
    {
        name: "Radiowave Journey",
        speciality: "RUPTURE",
        WengineStatSelected: "HP_PERCENT",
        WengineFlatAttack: 594,
        WengineStatValue: 25,
    },
    {
        name: "Puzzle Sphere",
        speciality: "RUPTURE",
        WengineStatSelected: "ATTACK_PERCENT",
        WengineFlatAttack: 594,
        WengineStatValue: 25,
    },
    {
        name: "Qingming Birdcage",
        speciality: "RUPTURE",
        WengineStatSelected: "HP_PERCENT",
        WengineFlatAttack: 743,
        WengineStatValue: 30,
    },
    {
        name: "Myriad Eclipse",
        speciality: "ATTACK",
        WengineStatSelected: "CRIT_RATE",
        WengineFlatAttack: 713,
        WengineStatValue: 24,
    },
    {
        name: "Timeweaver",
        speciality: "ANOMALY",
        WengineStatSelected: "ATTACK_PERCENT",
        WengineFlatAttack: 713,
        WengineStatValue: 30,
    },
    {
        name: "Flight of Fancy",
        speciality: "ANOMALY",
        WengineStatSelected: "ANOMALY_PROFICIENCY_FLAT",
        WengineFlatAttack: 713,
        WengineStatValue: 90,
    },
    {
        name: "Spectral Gaze",
        speciality: "STUN",
        WengineStatSelected: "CRIT_RATE",
        WengineFlatAttack: 713,
        WengineStatValue: 24,
    },
    {
        name: "Box Cutter",
        speciality: "STUN",
        WengineStatSelected: "IMPACT_FLAT",
        WengineFlatAttack: 624,
        WengineStatValue: 15,
    },
    {
        name: "Severed Innocence",
        speciality: "ATTACK",
        WengineStatSelected: "CRIT_DAMAGE",
        WengineFlatAttack: 713,
        WengineStatValue: 48,
    },
    {
        name: "Heartstring Nocturne",
        speciality: "ATTACK",
        WengineStatSelected: "CRIT_RATE",
        WengineFlatAttack: 713,
        WengineStatValue: 24,
    },
    {
        name: "Elegant Vanity",
        speciality: "SUPPORT",
        WengineStatSelected: "ATTACK_PERCENT",
        WengineFlatAttack: 713,
        WengineStatValue: 30,
    },
    {
        name: "Marcato Desire",
        speciality: "ATTACK",
        WengineStatSelected: "CRIT_RATE",
        WengineFlatAttack: 594,
        WengineStatValue: 20,
    },
    {
        name: "Hailstorm Shrine",
        speciality: "ANOMALY",
        WengineStatSelected: "CRIT_RATE",
        WengineFlatAttack: 743,
        WengineStatValue: 24,
    },
    {
        name: "Zanshin Herb Case",
        speciality: "ATTACK",
        WengineStatSelected: "CRIT_DAMAGE",
        WengineFlatAttack: 713,
        WengineStatValue: 48,
    },
    {
        name: "Blazing Laurel",
        speciality: "STUN",
        WengineStatSelected: "IMPACT_FLAT",
        WengineFlatAttack: 713,
        WengineStatValue: 18,
    },
    {
        name: "Hellfire Gears",
        speciality: "STUN",
        WengineStatSelected: "IMPACT_FLAT",
        WengineFlatAttack: 684,
        WengineStatValue: 18,
    },
    {
        name: "Flamemaker Shaker",
        speciality: "ANOMALY",
        WengineStatSelected: "ATTACK_PERCENT",
        WengineFlatAttack: 713,
        WengineStatValue: 30,
    },
    {
        name: "Demara Battery Mark II",
        speciality: "STUN",
        WengineStatSelected: "IMPACT_FLAT",
        WengineFlatAttack: 624,
        WengineStatValue: 15,
    },
    {
        name: "Tusks of Fury",
        speciality: "DEFENSE",
        WengineStatSelected: "IMPACT_FLAT",
        WengineFlatAttack: 713,
        WengineStatValue: 18,
    },
    {
        name: "Ice-Jade Teapot",
        speciality: "STUN",
        WengineStatSelected: "IMPACT_FLAT",
        WengineFlatAttack: 713,
        WengineStatValue: 18,
    },
    {
        name: "Peacekeeper - Specialized",
        speciality: "DEFENSE",
        WengineStatSelected: "ATTACK_PERCENT",
        WengineFlatAttack: 624,
        WengineStatValue: 25,
    },
    {
        name: "Sharpened Stinger",
        speciality: "ANOMALY",
        WengineStatSelected: "ANOMALY_PROFICIENCY_FLAT",
        WengineFlatAttack: 713,
        WengineStatValue: 90,
    },
    {
        name: "Gilded Blossom",
        speciality: "ATTACK",
        WengineStatSelected: "ATTACK_PERCENT",
        WengineFlatAttack: 594,
        WengineStatValue: 25,
    },
    {
        name: "Kaboom the Cannon",
        speciality: "SUPPORT",
        WengineStatSelected: "ENERGY_REGEN_PERCENT",
        WengineFlatAttack: 624,
        WengineStatValue: 50,
    },
    {
        name: "Roaring Ride",
        speciality: "ANOMALY",
        WengineStatSelected: "ATTACK_PERCENT",
        WengineFlatAttack: 624,
        WengineStatValue: 25,
    },
    {
        name: "Riot Suppressor Mark VI",
        speciality: "ATTACK",
        WengineStatSelected: "CRIT_DAMAGE",
        WengineFlatAttack: 713,
        WengineStatValue: 48,
    },
    {
        name: "Deep Sea Visitor",
        speciality: "ATTACK",
        WengineStatSelected: "CRIT_RATE",
        WengineFlatAttack: 713,
        WengineStatValue: 24,
    },
    {
        name: "Weeping Gemini",
        speciality: "ANOMALY",
        WengineStatSelected: "ATTACK_PERCENT",
        WengineFlatAttack: 594,
        WengineStatValue: 25,
    },
    {
        name: "Weeping Cradle",
        speciality: "SUPPORT",
        WengineStatSelected: "PEN_PERCENT",
        WengineFlatAttack: 684,
        WengineStatValue: 24,
    },
    {
        name: "Unfettered Game Ball",
        speciality: "SUPPORT",
        WengineStatSelected: "ENERGY_REGEN_PERCENT",
        WengineFlatAttack: 594,
        WengineStatValue: 50,
    },
    {
        name: "The Vault",
        speciality: "SUPPORT",
        WengineStatSelected: "ENERGY_REGEN_PERCENT",
        WengineFlatAttack: 624,
        WengineStatValue: 50,
    },
    {
        name: "The Restrained",
        speciality: "STUN",
        WengineStatSelected: "IMPACT_FLAT",
        WengineFlatAttack: 684,
        WengineStatValue: 18,
    },
    {
        name: "The Brimstone",
        speciality: "ATTACK",
        WengineStatSelected: "ATTACK_PERCENT",
        WengineFlatAttack: 684,
        WengineStatValue: 30,
    },
    {
        name: "Street Superstar",
        speciality: "ATTACK",
        WengineStatSelected: "ATTACK_PERCENT",
        WengineFlatAttack: 594,
        WengineStatValue: 25,
    },
    {
        name: "Steel Cushion",
        speciality: "ATTACK",
        WengineStatSelected: "CRIT_RATE",
        WengineFlatAttack: 684,
        WengineStatValue: 24,
    },
    {
        name: "Steam Oven",
        speciality: "STUN",
        WengineStatSelected: "ENERGY_REGEN_PERCENT",
        WengineFlatAttack: 594,
        WengineStatValue: 50,
    },
    {
        name: "Starlight Engine Replica",
        speciality: "ATTACK",
        WengineStatSelected: "ATTACK_PERCENT",
        WengineFlatAttack: 624,
        WengineStatValue: 25,
    },
    {
        name: "Starlight Engine",
        speciality: "ATTACK",
        WengineStatSelected: "ATTACK_PERCENT",
        WengineFlatAttack: 594,
        WengineStatValue: 25,
    },
    {
        name: "Spring Embrace",
        speciality: "DEFENSE",
        WengineStatSelected: "ATTACK_PERCENT",
        WengineFlatAttack: 594,
        WengineStatValue: 25,
    },
    {
        name: "Slice of Time",
        speciality: "ATTACK",
        WengineStatSelected: "PEN_PERCENT",
        WengineFlatAttack: 594,
        WengineStatValue: 20,
    },
    {
        name: "Six Shooter",
        speciality: "STUN",
        WengineStatSelected: "IMPACT_FLAT",
        WengineFlatAttack: 594,
        WengineStatValue: 15,
    },
    {
        name: "Rainforest Gourmet",
        speciality: "ANOMALY",
        WengineStatSelected: "ANOMALY_PROFICIENCY_FLAT",
        WengineFlatAttack: 594,
        WengineStatValue: 75,
    },
    {
        name: "Precious Fossilized Core",
        speciality: "STUN",
        WengineStatSelected: "IMPACT_FLAT",
        WengineFlatAttack: 594,
        WengineStatValue: 15,
    },
    {
        name: "Original Transmorpher",
        speciality: "DEFENSE",
        WengineStatSelected: "HP_PERCENT",
        WengineFlatAttack: 594,
        WengineStatValue: 25,
    },
    {
        name: "Housekeeper",
        speciality: "ATTACK",
        WengineStatSelected: "ATTACK_PERCENT",
        WengineFlatAttack: 624,
        WengineStatValue: 25,
    },
    {
        name: "Fusion Compiler",
        speciality: "ANOMALY",
        WengineStatSelected: "PEN_PERCENT",
        WengineFlatAttack: 684,
        WengineStatValue: 24,
    },
    {
        name: "Electro-Lip Gloss",
        speciality: "ANOMALY",
        WengineStatSelected: "ANOMALY_PROFICIENCY_FLAT",
        WengineFlatAttack: 594,
        WengineStatValue: 75,
    },
    {
        name: "Drill Rig - Red Axis",
        speciality: "ATTACK",
        WengineStatSelected: "ENERGY_REGEN_PERCENT",
        WengineFlatAttack: 624,
        WengineStatValue: 50,
    },
    {
        name: "Cannon Rotor",
        speciality: "ATTACK",
        WengineStatSelected: "CRIT_RATE",
        WengineFlatAttack: 594,
        WengineStatValue: 20,
    },
    {
        name: "Bunny Band",
        speciality: "DEFENSE",
        WengineStatSelected: "DEFENSE_PERCENT",
        WengineFlatAttack: 594,
        WengineStatValue: 40,
    },
    {
        name: "Big Cylinder",
        speciality: "DEFENSE",
        WengineStatSelected: "DEFENSE_PERCENT",
        WengineFlatAttack: 624,
        WengineStatValue: 40,
    },
    {
        name: "Bashful Demon",
        speciality: "SUPPORT",
        WengineStatSelected: "ATTACK_PERCENT",
        WengineFlatAttack: 624,
        WengineStatValue: 25,
    },
    {
        name: "[Vortex] Revolver",
        speciality: "STUN",
        WengineStatSelected: "ATTACK_PERCENT",
        WengineFlatAttack: 475,
        WengineStatValue: 20,
    },
    {
        name: "[Vortex] Hatchet",
        speciality: "STUN",
        WengineStatSelected: "ENERGY_REGEN_PERCENT",
        WengineFlatAttack: 475,
        WengineStatValue: 16,
    },
    {
        name: "[Vortex] Arrow",
        speciality: "STUN",
        WengineStatSelected: "IMPACT_FLAT",
        WengineFlatAttack: 475,
        WengineStatValue: 12,
    },
    {
        name: "[Reverb] Mark III",
        speciality: "SUPPORT",
        WengineStatSelected: "HP_PERCENT",
        WengineFlatAttack: 475,
        WengineStatValue: 20,
    },
    {
        name: "[Reverb] Mark II",
        speciality: "SUPPORT",
        WengineStatSelected: "ENERGY_REGEN_PERCENT",
        WengineFlatAttack: 475,
        WengineStatValue: 40,
    },
    {
        name: "[Reverb] Mark I",
        speciality: "SUPPORT",
        WengineStatSelected: "ATTACK_PERCENT",
        WengineFlatAttack: 475,
        WengineStatValue: 20,
    },
    {
        name: "[Magnetic Storm] Charlie",
        speciality: "ANOMALY",
        WengineStatSelected: "PEN_PERCENT",
        WengineFlatAttack: 475,
        WengineStatValue: 16,
    },
    {
        name: "[Magnetic Storm] Bravo",
        speciality: "ANOMALY",
        WengineStatSelected: "ANOMALY_PROFICIENCY_FLAT",
        WengineFlatAttack: 475,
        WengineStatValue: 60,
    },
    {
        name: "[Magnetic Storm] Alpha",
        speciality: "ANOMALY",
        WengineStatSelected: "ATTACK_PERCENT",
        WengineFlatAttack: 475,
        WengineStatValue: 20,
    },
    {
        name: "[Lunar] Pleniluna",
        speciality: "ATTACK",
        WengineStatSelected: "ATTACK_PERCENT",
        WengineFlatAttack: 475,
        WengineStatValue: 20,
    },
    {
        name: "[Lunar] Noviluna",
        speciality: "ATTACK",
        WengineStatSelected: "CRIT_RATE",
        WengineFlatAttack: 475,
        WengineStatValue: 16,
    },
    {
        name: "[Lunar] Decrescent",
        speciality: "ATTACK",
        WengineStatSelected: "ATTACK_PERCENT",
        WengineFlatAttack: 475,
        WengineStatValue: 20,
    },
    {
        name: "[Identity] Inflection",
        speciality: "DEFENSE",
        WengineStatSelected: "DEFENSE_PERCENT",
        WengineFlatAttack: 475,
        WengineStatValue: 32,
    },
    {
        name: "[Identity] Base",
        speciality: "DEFENSE",
        WengineStatSelected: "DEFENSE_PERCENT",
        WengineFlatAttack: 475,
        WengineStatValue: 32,
    },
    {
        name: "None",
        speciality: "DEFENSE",
        WengineStatSelected: "NONE",
        WengineFlatAttack: 0,
        WengineStatValue: 0
    }
];
