import type { Wengine } from "./types";

export const Wengines: Wengine[] = [
    {
        name: "[Vortex] Revolver",
        id: 12007,
        speciality: "STUN",
        WengineStatSelected: "ATTACK_PERCENT",
        WengineFlatAttack: 475,
        WengineStatValue: 20,
    },
    {
        name: "[Vortex] Hatchet",
        id: 12009,
        speciality: "STUN",
        WengineStatSelected: "ENERGY_REGEN_PERCENT",
        WengineFlatAttack: 475,
        WengineStatValue: 16,
    },
    {
        name: "[Vortex] Arrow",
        id: 12008,
        speciality: "STUN",
        WengineStatSelected: "IMPACT_FLAT",
        WengineFlatAttack: 475,
        WengineStatValue: 12,
    },
    {
        name: "[Reverb] Mark III",
        id: 12006,
        speciality: "SUPPORT",
        WengineStatSelected: "HP_PERCENT",
        WengineFlatAttack: 475,
        WengineStatValue: 20,
    },
    {
        name: "[Reverb] Mark II",
        id: 12005,
        speciality: "SUPPORT",
        WengineStatSelected: "ENERGY_REGEN_PERCENT",
        WengineFlatAttack: 475,
        WengineStatValue: 40,
    },
    {
        name: "[Reverb] Mark I",
        id: 12004,
        speciality: "SUPPORT",
        WengineStatSelected: "ATTACK_PERCENT",
        WengineFlatAttack: 475,
        WengineStatValue: 20,
    },
    {
        name: "[Magnetic Storm] Charlie",
        id: 12012,
        speciality: "ANOMALY",
        WengineStatSelected: "PEN_PERCENT",
        WengineFlatAttack: 475,
        WengineStatValue: 16,
    },
    {
        name: "[Magnetic Storm] Bravo",
        id: 12011,
        speciality: "ANOMALY",
        WengineStatSelected: "ANOMALY_PROFICIENCY_FLAT",
        WengineFlatAttack: 475,
        WengineStatValue: 60,
    },
    {
        name: "[Magnetic Storm] Alpha",
        id: 12010,
        speciality: "ANOMALY",
        WengineStatSelected: "ATTACK_PERCENT",
        WengineFlatAttack: 475,
        WengineStatValue: 20,
    },
    {
        name: "[Lunar] Pleniluna",
        id: 12001,
        speciality: "ATTACK",
        WengineStatSelected: "ATTACK_PERCENT",
        WengineFlatAttack: 475,
        WengineStatValue: 20,
    },
    {
        name: "[Lunar] Noviluna",
        id: 12003,
        speciality: "ATTACK",
        WengineStatSelected: "CRIT_RATE",
        WengineFlatAttack: 475,
        WengineStatValue: 16,
    },
    {
        name: "[Lunar] Decrescent",
        id: 12002,
        speciality: "ATTACK",
        WengineStatSelected: "ATTACK_PERCENT",
        WengineFlatAttack: 475,
        WengineStatValue: 20,
    },
    {
        name: "[Identity] Inflection",
        id: 12014,
        speciality: "DEFENSE",
        WengineStatSelected: "DEFENSE_PERCENT",
        WengineFlatAttack: 475,
        WengineStatValue: 32,
    },
    {
        name: "[Identity] Base",
        id: 12013,
        speciality: "DEFENSE",
        WengineStatSelected: "DEFENSE_PERCENT",
        WengineFlatAttack: 475,
        WengineStatValue: 32,
    },
    {
        name: "[Cinder] Cobalt",
        id: 12015,
        speciality: "RUPTURE",
        WengineStatSelected: "HP_PERCENT",
        WengineFlatAttack: 475,
        WengineStatValue: 20,
    },
    {
        name: "Reel Projector",
        id: 13016,
        speciality: "DEFENSE",
        WengineStatSelected: "IMPACT_FLAT",
        WengineFlatAttack: 594,
        WengineStatValue: 15,
    },
    {
        name: "Radiowave Journey",
        id: 13014,
        speciality: "RUPTURE",
        WengineStatSelected: "HP_PERCENT",
        WengineFlatAttack: 594,
        WengineStatValue: 25,
    },
    {
        name: "Puzzle Sphere",
        id: 13012,
        speciality: "RUPTURE",
        WengineStatSelected: "ATTACK_PERCENT",
        WengineFlatAttack: 594,
        WengineStatValue: 25,
    },
    {
        name: "Marcato Desire",
        id: 13015,
        speciality: "ATTACK",
        WengineStatSelected: "CRIT_RATE",
        WengineFlatAttack: 594,
        WengineStatValue: 20,
    },
    {
        name: "Gilded Blossom",
        id: 13013,
        speciality: "ATTACK",
        WengineStatSelected: "ATTACK_PERCENT",
        WengineFlatAttack: 594,
        WengineStatValue: 25,
    },
    {
        name: "Weeping Cradle",
        id: 14121,
        speciality: "SUPPORT",
        WengineStatSelected: "PEN_PERCENT",
        WengineFlatAttack: 684,
        WengineStatValue: 24,
    },
    {
        name: "Unfettered Game Ball",
        id: 14002,
        speciality: "SUPPORT",
        WengineStatSelected: "ENERGY_REGEN_PERCENT",
        WengineFlatAttack: 594,
        WengineStatValue: 50,
    },
    {
        name: "Street Superstar",
        id: 13001,
        speciality: "ATTACK",
        WengineStatSelected: "ATTACK_PERCENT",
        WengineFlatAttack: 594,
        WengineStatValue: 25,
    },
    {
        name: "Steam Oven",
        id: 13005,
        speciality: "STUN",
        WengineStatSelected: "ENERGY_REGEN_PERCENT",
        WengineFlatAttack: 594,
        WengineStatValue: 50,
    },
    {
        name: "Starlight Engine",
        id: 13004,
        speciality: "ATTACK",
        WengineStatSelected: "ATTACK_PERCENT",
        WengineFlatAttack: 594,
        WengineStatValue: 25,
    },
    {
        name: "Spring Embrace",
        id: 13011,
        speciality: "DEFENSE",
        WengineStatSelected: "ATTACK_PERCENT",
        WengineFlatAttack: 594,
        WengineStatValue: 25,
    },
    {
        name: "Slice of Time",
        id: 13002,
        speciality: "ATTACK",
        WengineStatSelected: "PEN_PERCENT",
        WengineFlatAttack: 594,
        WengineStatValue: 20,
    },
    {
        name: "Six Shooter",
        id: 14003,
        speciality: "STUN",
        WengineStatSelected: "IMPACT_FLAT",
        WengineFlatAttack: 594,
        WengineStatValue: 15,
    },
    {
        name: "Rainforest Gourmet",
        id: 13003,
        speciality: "ANOMALY",
        WengineStatSelected: "ANOMALY_PROFICIENCY_FLAT",
        WengineFlatAttack: 594,
        WengineStatValue: 75,
    },
    {
        name: "Precious Fossilized Core",
        id: 13006,
        speciality: "STUN",
        WengineStatSelected: "IMPACT_FLAT",
        WengineFlatAttack: 594,
        WengineStatValue: 15,
    },
    {
        name: "Original Transmorpher",
        id: 13007,
        speciality: "DEFENSE",
        WengineStatSelected: "HP_PERCENT",
        WengineFlatAttack: 594,
        WengineStatValue: 25,
    },
    {
        name: "Electro-Lip Gloss",
        id: 13009,
        speciality: "ANOMALY",
        WengineStatSelected: "ANOMALY_PROFICIENCY_FLAT",
        WengineFlatAttack: 594,
        WengineStatValue: 75,
    },
    {
        name: "Cannon Rotor",
        id: 14001,
        speciality: "ATTACK",
        WengineStatSelected: "CRIT_RATE",
        WengineFlatAttack: 594,
        WengineStatValue: 20,
    },

    {
        name: "Half-Sugar Bunny",
        id: 14134,
        speciality: "DEFENSE",
        WengineStatSelected: "HP_PERCENT",
        WengineFlatAttack: 713,
        WengineStatValue: 30,
    },
    {
        name: "None",
        id: 0,
        speciality: "DEFENSE",
        WengineStatSelected: "NONE",
        WengineFlatAttack: 0,
        WengineStatValue: 0,
    },
    {
        name: "The Vault",
        id: 13103,
        speciality: "SUPPORT",
        WengineStatSelected: "ENERGY_REGEN_PERCENT",
        WengineFlatAttack: 624,
        WengineStatValue: 50,
    },
    {
        name: "Big Cylinder",
        id: 13112,
        speciality: "DEFENSE",
        WengineStatSelected: "DEFENSE_PERCENT",
        WengineFlatAttack: 624,
        WengineStatValue: 40,
    },
    {
        name: "Demara Battery Mark II",
        id: 13101,
        speciality: "STUN",
        WengineStatSelected: "IMPACT_FLAT",
        WengineFlatAttack: 624,
        WengineStatValue: 15,
    },
    {
        name: "Kaboom the Cannon",
        id: 13115,
        speciality: "SUPPORT",
        WengineStatSelected: "ENERGY_REGEN_PERCENT",
        WengineFlatAttack: 624,
        WengineStatValue: 50,
    },
    {
        name: "Bashful Demon",
        id: 13113,
        speciality: "SUPPORT",
        WengineStatSelected: "ATTACK_PERCENT",
        WengineFlatAttack: 624,
        WengineStatValue: 25,
    },
    {
        name: "Weeping Gemini",
        id: 14121,
        speciality: "ANOMALY",
        WengineStatSelected: "ATTACK_PERCENT",
        WengineFlatAttack: 594,
        WengineStatValue: 25,
    },
    {
        name: "The Restrained",
        id: 14114,
        speciality: "STUN",
        WengineStatSelected: "IMPACT_FLAT",
        WengineFlatAttack: 684,
        WengineStatValue: 18,
    },
    {
        name: "Hellfire Gears",
        id: 14110,
        speciality: "STUN",
        WengineStatSelected: "IMPACT_FLAT",
        WengineFlatAttack: 684,
        WengineStatValue: 18,
    },
    {
        name: "Roaring Ride",
        id: 13128,
        speciality: "ANOMALY",
        WengineStatSelected: "ATTACK_PERCENT",
        WengineFlatAttack: 624,
        WengineStatValue: 25,
    },
    {
        name: "Starlight Engine Replica",
        id: 13108,
        speciality: "ATTACK",
        WengineStatSelected: "ATTACK_PERCENT",
        WengineFlatAttack: 624,
        WengineStatValue: 25,
    },
    {
        name: "Drill Rig - Red Axis",
        id: 13111,
        speciality: "ATTACK",
        WengineStatSelected: "ENERGY_REGEN_PERCENT",
        WengineFlatAttack: 624,
        WengineStatValue: 50,
    },
    {
        name: "Housekeeper",
        id: 13106,
        speciality: "ATTACK",
        WengineStatSelected: "ATTACK_PERCENT",
        WengineFlatAttack: 624,
        WengineStatValue: 25,
    },
    {
        name: "Fusion Compiler",
        id: 14118,
        speciality: "ANOMALY",
        WengineStatSelected: "PEN_PERCENT",
        WengineFlatAttack: 684,
        WengineStatValue: 24,
    },
    {
        name: "The Brimstone",
        id: 14104,
        speciality: "ATTACK",
        WengineStatSelected: "ATTACK_PERCENT",
        WengineFlatAttack: 684,
        WengineStatValue: 30,
    },
    {
        name: "Steel Cushion",
        id: 14102,
        speciality: "ATTACK",
        WengineStatSelected: "CRIT_RATE",
        WengineFlatAttack: 684,
        WengineStatValue: 24,
    },
    {
        name: "Riot Suppressor Mark VI",
        id: 14124,
        speciality: "ATTACK",
        WengineStatSelected: "CRIT_DAMAGE",
        WengineFlatAttack: 713,
        WengineStatValue: 48,
    },
    {
        name: "Deep Sea Visitor",
        id: 14119,
        speciality: "ATTACK",
        WengineStatSelected: "CRIT_RATE",
        WengineFlatAttack: 713,
        WengineStatValue: 24,
    },
    {
        name: "Ice-Jade Teapot",
        id: 14125,
        speciality: "STUN",
        WengineStatSelected: "IMPACT_FLAT",
        WengineFlatAttack: 713,
        WengineStatValue: 18,
    },
    {
        name: "Sharpened Stinger",
        id: 14126,
        speciality: "ANOMALY",
        WengineStatSelected: "ANOMALY_PROFICIENCY_FLAT",
        WengineFlatAttack: 713,
        WengineStatValue: 90,
    },
    {
        name: "Peacekeeper - Specialized",
        id: 13127,
        speciality: "DEFENSE",
        WengineStatSelected: "ATTACK_PERCENT",
        WengineFlatAttack: 624,
        WengineStatValue: 25,
    },
    {
        name: "Tusks of Fury",
        id: 14107,
        speciality: "DEFENSE",
        WengineStatSelected: "IMPACT_FLAT",
        WengineFlatAttack: 713,
        WengineStatValue: 18,
    },
    {
        name: "Flamemaker Shaker",
        id: 14117,
        speciality: "ANOMALY",
        WengineStatSelected: "ATTACK_PERCENT",
        WengineFlatAttack: 713,
        WengineStatValue: 30,
    },
    {
        name: "Timeweaver",
        id: 14122,
        speciality: "ANOMALY",
        WengineStatSelected: "ATTACK_PERCENT",
        WengineFlatAttack: 713,
        WengineStatValue: 30,
    },
    {
        name: "Blazing Laurel",
        id: 14116,
        speciality: "STUN",
        WengineStatSelected: "IMPACT_FLAT",
        WengineFlatAttack: 713,
        WengineStatValue: 18,
    },
    {
        name: "Hailstorm Shrine",
        id: 14109,
        speciality: "ANOMALY",
        WengineStatSelected: "CRIT_RATE",
        WengineFlatAttack: 743,
        WengineStatValue: 24,
    },
    {
        name: "Zanshin Herb Case",
        id: 14120,
        speciality: "ATTACK",
        WengineStatSelected: "CRIT_DAMAGE",
        WengineFlatAttack: 713,
        WengineStatValue: 48,
    },
    {
        name: "Elegant Vanity",
        id: 14131,
        speciality: "SUPPORT",
        WengineStatSelected: "ATTACK_PERCENT",
        WengineFlatAttack: 713,
        WengineStatValue: 30,
    },
    {
        name: "Heartstring Nocturne",
        id: 14132,
        speciality: "ATTACK",
        WengineStatSelected: "CRIT_RATE",
        WengineFlatAttack: 713,
        WengineStatValue: 24,
    },
    {
        name: "Severed Innocence",
        id: 14138,
        speciality: "ATTACK",
        WengineStatSelected: "CRIT_DAMAGE",
        WengineFlatAttack: 713,
        WengineStatValue: 48,
    },
    {
        name: "Box Cutter",
        id: 13135,
        speciality: "STUN",
        WengineStatSelected: "IMPACT_FLAT",
        WengineFlatAttack: 624,
        WengineStatValue: 15,
    },
    {
        name: "Spectral Gaze",
        id: 14136,
        speciality: "STUN",
        WengineStatSelected: "CRIT_RATE",
        WengineFlatAttack: 713,
        WengineStatValue: 24,
    },
    {
        name: "Flight of Fancy",
        id: 14133,
        speciality: "ANOMALY",
        WengineStatSelected: "ANOMALY_PROFICIENCY_FLAT",
        WengineFlatAttack: 713,
        WengineStatValue: 90,
    },
    {
        name: "Myriad Eclipse",
        id: 14129,
        speciality: "ATTACK",
        WengineStatSelected: "CRIT_RATE",
        WengineFlatAttack: 713,
        WengineStatValue: 24,
    },
    {
        name: "Tremor Trigram Vessel",
        id: 13142,
        speciality: "DEFENSE",
        WengineStatSelected: "ATTACK_PERCENT",
        WengineFlatAttack: 624,
        WengineStatValue: 25,
    },
    {
        name: "Qingming Birdcage",
        id: 14137,
        speciality: "RUPTURE",
        WengineStatSelected: "HP_PERCENT",
        WengineFlatAttack: 743,
        WengineStatValue: 30,
    },
    {
        name: "Roaring Fur-nace",
        id: 13128,
        speciality: "STUN",
        WengineStatSelected: "ATTACK_PERCENT",
        WengineFlatAttack: 713,
        WengineStatValue: 30,
    },
    {
        name: "Metanukimorphosis",
        id: 14141,
        speciality: "SUPPORT",
        WengineStatSelected: "ENERGY_REGEN_PERCENT",
        WengineFlatAttack: 713,
        WengineStatValue: 60,
    },
    {
        name: "Practiced Perfection",
        id: 14140,
        speciality: "ANOMALY",
        WengineStatSelected: "ATTACK_PERCENT",
        WengineFlatAttack: 713,
        WengineStatValue: 30,
    },
    {
        name: "Cordis Germina",
        id: 14146,
        speciality: "ATTACK",
        WengineStatSelected: "CRIT_RATE",
        WengineFlatAttack: 713,
        WengineStatValue: 24,
    },
    {
        name: "Bellicose Blaze",
        id: 14130,
        speciality: "ATTACK",
        WengineStatSelected: "ENERGY_REGEN_PERCENT",
        WengineFlatAttack: 713,
        WengineStatValue: 60,
    },
    {
        name: "Dreamlit Hearth",
        id: 14145,
        speciality: "SUPPORT",
        WengineStatSelected: "HP_PERCENT",
        WengineFlatAttack: 713,
        WengineStatValue: 30,
    },
    {
        name: "Grill O'Wisp",
        id: 13144,
        speciality: "RUPTURE",
        WengineStatSelected: "HP_PERCENT",
        WengineFlatAttack: 624,
        WengineStatValue: 25,
    },
    {
        name: "Kraken's Cradle",
        id: 14105,
        speciality: "RUPTURE",
        WengineStatSelected: "HP_PERCENT",
        WengineFlatAttack: 713,
        WengineStatValue: 30,
    },
    {
        name: "Yesterday Calls",
        id: 14148,
        speciality: "STUN",
        WengineStatSelected: "CRIT_RATE",
        WengineFlatAttack: 713,
        WengineStatValue: 24,
    },
    {
        name: "Wrathful Vajra",
        id: 14147,
        speciality: "RUPTURE",
        WengineStatSelected: "HP_PERCENT",
        WengineFlatAttack: 713,
        WengineStatValue: 30,
    },
    {
        name: "Bunny Band",
        id: 13010,
        speciality: "DEFENSE",
        WengineStatSelected: "DEFENSE_PERCENT",
        WengineFlatAttack: 594,
        WengineStatValue: 40,
    },
    {
        name: "Cloudcleave Radiance",
        id: 14143,
        speciality: "ATTACK",
        WengineStatSelected: "CRIT_DAMAGE",
        WengineFlatAttack: 743,
        WengineStatValue: 48,
    },
];
